#!/usr/bin/env bash
# this transfers a file from the client to the server
# path
# ip="$2"
# usernmae="$3"
# path_to_ssh_key="$4"
# theres strict host key checkung must be disabled when using scp

# check if less than 3 parameters are provided

if [ $# -lt 4 ]
then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
	scp -0 StrictHostKeyChecking=no -i "$4" "$1" "$3@$2":~
fi 



