#!/usr/bin/env bash
#This script should display "To infinity and beyond" indefinitely
#With a sleep
#Displays "I am invincible!!!"

while true
do
	echo "To infinity and beyond"
	sleep 2

	trap 'echo "I am invincible!!!"' SIGTERM
done
